### ISSUE TITLE
error raise in '2015-02-16-raspbian-wheezy.zip' image

### ISSUE THREAD

**Issue by gbox3d** [voodootikigod/node-serialport#485]
child_process: customFds option is deprecated, use stdio instead.
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/work/node_modules/serialport/.node-gyp"
gyp ERR! Completion callback never invoked! 
gyp ERR! System Linux 3.18.7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=serialport" "--configuration=Release" "--module_name=serialport" "--version=1.6.2" "--major=1" "--minor=6" "--patch=2" "--runtime=node" "--node_abi=node-v14" "--platform=linux" "--target_platform=linux" "--arch=arm" "--target_arch=arm" "--module_main=./serialport" "--host=https://node-serialport.s3.amazonaws.com/" "--module_path=/home/pi/work/node_modules/serialport/build/serialport/v1.6.2/Release/node-v14-linux-arm" "--remote_path=./serialport/v1.6.2/Release/" "--package_name=node-v14-linux-arm.tar.gz" "--staged_tarball=build/stage/serialport/v1.6.2/Release/node-v14-linux-arm.tar.gz" "--hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.6.2/Release/" "--hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.6.2/Release/node-v14-linux-arm.tar.gz"
gyp ERR! cwd /home/pi/work/node_modules/serialport
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.6.2 --major=1 --minor=6 --patch=2 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/home/pi/work/node_modules/serialport/build/serialport/v1.6.2/Release/node-v14-linux-arm --remote_path=./serialport/v1.6.2/Release/ --package_name=node-v14-linux-arm.tar.gz --staged_tarball=build/stage/serialport/v1.6.2/Release/node-v14-linux-arm.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.6.2/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.6.2/Release/node-v14-linux-arm.tar.gz' (6)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/work/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Linux 3.18.7+
node-pre-gyp ERR! command "node" "/home/pi/work/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/work/node_modules/serialport
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.5.19
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node rebuild --name=serialport --configuration=Release --module_name=serialport --version=1.6.2 --major=1 --minor=6 --patch=2 --runtime=node --node_abi=node-v14 --platform=linux --target_platform=linux --arch=arm --target_arch=arm --module_main=./serialport --host=https://node-serialport.s3.amazonaws.com/ --module_path=/home/pi/work/node_modules/serialport/build/serialport/v1.6.2/Release/node-v14-linux-arm --remote_path=./serialport/v1.6.2/Release/ --package_name=node-v14-linux-arm.tar.gz --staged_tarball=build/stage/serialport/v1.6.2/Release/node-v14-linux-arm.tar.gz --hosted_path=https://node-serialport.s3.amazonaws.com/serialport/v1.6.2/Release/ --hosted_tarball=https://node-serialport.s3.amazonaws.com/serialport/v1.6.2/Release/node-v14-linux-arm.tar.gz' (6)
npm ERR! Linux 3.18.7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "serialport"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! serialport@1.6.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@1.6.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/work/npm-debug.log

**Comment by gbox3d** [comment]
this error raise in '2015-02-16-raspbian-wheezy.zip' image
but older version wheezy is no problem
why?

**Comment by gbox3d** [comment]
complete problem 
torrent downloaded image is wrong.
redownload at site it work well
