### ISSUE TITLE
Error: Compiling for Electron(Atom Shell)

### ISSUE THREAD

**Issue by sirwolfgang** [voodootikigod/node-serialport#522]
I am trying to recompile for use with Electron but am running into this error:
```
> serialport@1.6.3 install /Users/zpickett/Projects/tracker/node_modules/serialport
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.25.2

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Unsupported target version: 0.25.2
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/zpickett/Projects/tracker/node_modules/serialport/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/zpickett/Projects/tracker/node_modules/serialport/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/Users/zpickett/Projects/tracker/node_modules/serialport/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/zpickett/Projects/tracker/node_modules/serialport/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/zpickett/Projects/tracker/node_modules/serialport/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/zpickett/Projects/tracker/node_modules/serialport/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:431:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:449:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:311:12)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "/usr/local/bin/iojs" "/Users/zpickett/Projects/tracker/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/zpickett/Projects/tracker/node_modules/serialport
node-pre-gyp ERR! node -v v2.0.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
```

Version `0.25.2` is the electron version. I also seem unable to find/understand where the version is being locked/limited?

**Comment by LePhasme** [comment]
I've also tried everything I could find (including https://gist.github.com/jedthehumanoid/a7f8278e0a37d259adca) but in vain.

**Comment by voodootikigod** [comment]
https://github.com/voodootikigod/node-serialport/issues/538#issuecomment-115207973

**Comment by ddm** [comment]
If anybody stumbles upon this while trying to use `node-serialport` with electron: there is a temporary solution in the form of the `[serialport-electron](https://www.npmjs.com/package/serialport-electron)`.
Hopefully, in the long run, `node-pre-gyp` will support electron OOTB.
