### ISSUE TITLE
Fails to install with io.js v3.0.0 on Windows 

### ISSUE THREAD

**Issue by CubixSystem** [voodootikigod/node-serialport#562]
It seems like new version problem, I use io.js v 2.5 before and it works ok.

Win 8.1 x64

```cmd
>node -v
v3.0.0
```
```cmd
D:\Docs\Tests\serial-test>npm i serialport
npm WARN package.json serial-test@1.0.0 No description
npm WARN package.json serial-test@1.0.0 No repository field.
npm WARN package.json serial-test@1.0.0 No README data
/
> serialport@1.7.4 install D:\Docs\Tests\serial-test\node_modules\serialport
> node-pre-gyp install --fallback-to-build


D:\Docs\Tests\serial-test\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\iojs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node  clean )

D:\Docs\Tests\serial-test\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\iojs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" confi ure --fallback-to-build --module=D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport\v1.7.4\Release\node-v45-win32-x64\serialport.node --module_name=serialport --module_path=D:\Docs\Te ts\serial-test\node_modules\serialport\build\serialport\v1.7.4\Release\node-v45-win32-x64 )  else (node  configure --fallback-to-build --module=D:\Docs\Tests\serial-test\node_modules\serialport\build serialport\v1.7.4\Release\node-v45-win32-x64\serialport.node --module_name=serialport --module_path=D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport\v1.7.4\Release\node-v45-win32-x6  )

D:\Docs\Tests\serial-test\node_modules\serialport>if not defined npm_config_node_gyp (node "C:\Program Files\iojs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build --fallback-to-build --module=D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport\v1.7.4\Release\node-v45-win32-x64\serialport.node --module_name=serialport --module_path=D:\Docs\Tests\ erial-test\node_modules\serialport\build\serialport\v1.7.4\Release\node-v45-win32-x64 )  else (node  build --fallback-to-build --module=D:\Docs\Tests\serial-test\node_modules\serialport\build\serialp rt\v1.7.4\Release\node-v45-win32-x64\serialport.node --module_name=serialport --module_path=D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport\v1.7.4\Release\node-v45-win32-x64 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  serialport.cpp
  serialport_win.cpp
  enumser.cpp
..\src\win\enumser.cpp(443): warning C4996: 'GetVersionExA': was declared deprecated [D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport.vcxproj]
          C:\Program Files (x86)\Windows Kits\8.1\Include\um\sysinfoapi.h(433) : see declaration of 'GetVersionExA'
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)' : function template has already been defined (..\src\serialpor t.cpp) [D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport.vcxproj]
          D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(256) : see declaration of '_NanEnsureLocal'
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be a type (..\src\serialport.cpp) [D:\Docs\Tests\serial-te st\node_modules\serialport\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(661): error C2039: 'FreeCallback' : is not a member of 'node' (..\src\serialport.cpp) [D:\Docs\Tests\serial-test\node_modules\ serialport\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(661): error C2061: syntax error : identifier 'FreeCallback' (..\src\serialport.cpp) [D:\Docs\Tests\serial-test\node_modules\se rialport\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: 'callback' : undeclared identifier (..\src\serialport.cpp) [D:\Docs\Tests\serial-test\node_modules\serialpo rt\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: 'hint' : undeclared identifier (..\src\serialport.cpp) [D:\Docs\Tests\serial-test\node_modules\serialport\b uild\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(263): error C2995: 'v8::Local<T> _NanEnsureLocal(v8::Local<T>)' : function template has already been defined (..\src\serialpor t_win.cpp) [D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport.vcxproj]
          D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(256) : see declaration of '_NanEnsureLocal'
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(672): error C2665: 'node::Buffer::New' : none of the 4 overloads could convert all the argument types (..\src\serialport.cpp)
[D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport.vcxproj]
          C:\Users\Redfox\.node-gyp\3.0.0\include\node\node_buffer.h(47): could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
          C:\Users\Redfox\.node-gyp\3.0.0\include\node\node_buffer.h(35): or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(676): error C2664: 'v8::Local<v8::Object>::Local(const v8::Local<v8::Object> &)' : cannot convert argument 1 from 'v8::MaybeLo cal<v8::Object>' to 'const v8::Local<v8::Object> &' (..\src\serialport.cpp) [D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object>'
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(683): error C2039: 'Use' : is not a member of 'node::Buffer' (..\src\serialport.cpp) [D:\Docs\Tests\serial-test\node_modules\s erialport\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(683): error C3861: 'Use': identifier not found (..\src\serialport.cpp) [D:\Docs\Tests\serial-test\node_modules\serialport\buil d\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(661): error C3083: 'smalloc': the symbol to the left of a '::' must be a type (..\src\serialport_win.cpp) [D:\Docs\Tests\seria l-test\node_modules\serialport\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(661): error C2039: 'FreeCallback' : is not a member of 'node' (..\src\serialport_win.cpp) [D:\Docs\Tests\serial-test\node_modu les\serialport\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(661): error C2061: syntax error : identifier 'FreeCallback' (..\src\serialport_win.cpp) [D:\Docs\Tests\serial-test\node_module s\serialport\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: 'callback' : undeclared identifier (..\src\serialport_win.cpp) [D:\Docs\Tests\serial-test\node_modules\seri alport\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(665): error C2065: 'hint' : undeclared identifier (..\src\serialport_win.cpp) [D:\Docs\Tests\serial-test\node_modules\serialpo rt\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(672): error C2665: 'node::Buffer::New' : none of the 4 overloads could convert all the argument types (..\src\serialport_win.c pp) [D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport.vcxproj]
          C:\Users\Redfox\.node-gyp\3.0.0\include\node\node_buffer.h(47): could be 'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,char *,size_t)'
          C:\Users\Redfox\.node-gyp\3.0.0\include\node\node_buffer.h(35): or       'v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate *,v8::Local<v8::String>,node::encoding)'
          while trying to match the argument list '(v8::Isolate *, const char *, uint32_t)'
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(676): error C2664: 'v8::Local<v8::Object>::Local(const v8::Local<v8::Object> &)' : cannot convert argument 1 from 'v8::MaybeLo cal<v8::Object>' to 'const v8::Local<v8::Object> &' (..\src\serialport_win.cpp) [D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport.vcxproj]
          Reason: cannot convert from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object>'
          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(683): error C2039: 'Use' : is not a member of 'node::Buffer' (..\src\serialport_win.cpp) [D:\Docs\Tests\serial-test\node_modul es\serialport\build\serialport.vcxproj]
D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\nan\nan.h(683): error C3861: 'Use': identifier not found (..\src\serialport_win.cpp) [D:\Docs\Tests\serial-test\node_modules\serialport\ build\serialport.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\iojs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=D:\\Docs\\Tests\\se ial-test\\node_modules\\serialport\\build\\serialport\\v1.7.4\\Release\\node-v45-win32-x64\\serialport.node" "--module_name=serialport" "--module_path=D:\\Docs\\Tests\\serial-test\\node_modules\\seri lport\\build\\serialport\\v1.7.4\\Release\\node-v45-win32-x64"
gyp ERR! cwd D:\Docs\Tests\serial-test\node_modules\serialport
gyp ERR! node -v v3.0.0
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport\v1.7.4\Release\node-v45-win32-x64\ erialport.node --module_name=serialport --module_path=D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport\v1.7.4\Release\node-v45-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\Docs\Tests\serial-test\node_modules\serialport\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:764:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "D:\\Docs\\Tests\\serial-test\\node_modules\\serialport\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\Docs\Tests\serial-test\node_modules\serialport
node-pre-gyp ERR! node -v v3.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport\v1.7.4\Release\node-v45-win32-x64\serialport.node --module_name=s rialport --module_path=D:\Docs\Tests\serial-test\node_modules\serialport\build\serialport\v1.7.4\Release\node-v45-win32-x64' (1)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "i" "serialport"
npm ERR! node v3.0.0
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! serialport@1.7.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serialport@1.7.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Docs\Tests\serial-test\npm-debug.log
```

**Comment by jacobrosenthal** [comment]
Closing for #578
