### ISSUE TITLE
Cannot install on RPi2.

### ISSUE THREAD

**Issue by 4rzael** [voodootikigod/node-serialport#614]
Hello, I'm using serialport 1.7.4 for a project, but the `npm install` fails on a raspberry pi 2.

I tried using Raspbian Wheezy and an other debian Jessie, both failed.

* My version of node is 0.10.40
* My version of npm is 3.3.8

I get this error

```
npm WARN install Couldn't install optional dependency: Unsupported

> bufferutil@1.2.1 install /home/pi/6brain/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/6brain/node_modules/bufferutil/.node-gyp"
make: Entering directory '/home/pi/6brain/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/home/pi/6brain/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /home/pi/6brain/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/6brain/node_modules/utf-8-validate/.node-gyp"
make: Entering directory '/home/pi/6brain/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/pi/6brain/node_modules/utf-8-validate/build'

> serialport@1.7.4 install /home/pi/6brain/node_modules/serialport
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.40"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/6brain/node_modules/serialport/.node-gyp"
make: Entering directory '/home/pi/6brain/node_modules/serialport/build'
make: *** No rule to make target '../.node-gyp/0.10.40/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/pi/6brain/node_modules/serialport/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.1.8-hypriotos-v7+
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/pi/6brain/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node" "--module_name=serialport" "--module_path=/home/pi/6brain/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm"
gyp ERR! cwd /home/pi/6brain/node_modules/serialport
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp build --fallback-to-build --module=/home/pi/6brain/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/6brain/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/6brain/node_modules/serialport/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
node-pre-gyp ERR! System Linux 4.1.8-hypriotos-v7+
node-pre-gyp ERR! command "node" "/home/pi/6brain/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/6brain/node_modules/serialport
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 
Failed to execute 'node-gyp build --fallback-to-build --module=/home/pi/6brain/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm/serialport.node --module_name=serialport --module_path=/home/pi/6brain/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-arm' (1)
```

then

```
npm ERR! Linux 4.1.8-hypriotos-v7+
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.10.40
npm ERR! npm  v3.3.8
npm ERR! code ELIFECYCLE

npm ERR! serialport@1.7.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@1.7.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.
```
Do you have any idea about why it fails ?

**Comment by 4rzael** [comment]
Oops, sorry, duplicate from #535
